<a href="https://colab.research.google.com/github/lxxhxng/aipython/blob/main/240109.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [14]:
# 1. 1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자.

arr1 = np.arange(1, 10, 2)
print(arr1)

[1 3 5 7 9]


In [15]:
# 2. 모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자.

arr2 = np.ones((3, 4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# 3. 0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자.

arr3 = np.linspace(0, 1, 10)
print(arr3)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [49]:
# 1. A행렬을 생성해보자.

A = np.arange(1, 26).reshape(5, 5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [50]:
# 2. A의 모양(shape)을 출력해보자.

print(A.shape)

(5, 5)


In [51]:
# 3. 19 값을 추출해보자.

print(A[3, 3])

19


In [52]:
# 4. 슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출해보자

print(A[:2, :2])

[[1 2]
 [6 7]]


In [53]:
# 5. 슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출해보자.

print(A[3:, 3:])

[[19 20]
 [24 25]]


In [59]:
# 6. 슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자.
# 0축 : axis = 0 / 모든 행

print(A[:2, :])
print(A[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [58]:
# 7. 슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자.
# 1축 : axis = 1 / 모든 열

print(A[:, -2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [61]:
# 1. A행렬을 생성해보자.

A = np.arange(1, 37).reshape(3, 3, 4)
print(A)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [63]:
# 2. A 배열의 모양과 크기를 출력해보자.

print(A.shape)
print(A.size)

(3, 3, 4)
36


In [65]:
# 3. A의 모양을 (3, 4, 3)로 변경해보자.

A = A.reshape(3, 4, 3)
print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [67]:
# 4. A를 1차원 배열로 구성해보자.

A = A.flatten()
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
